services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: adil-compo-vs-inher
    restart: always
    working_dir: /var/www/html
    ports:
      - 8005:80
    volumes:
      - ../:/var/www/html